version: "3.9"

services:
  server:
    build: ./
    ports:
      - '8080:8080'
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:8.0.35
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    volumes:
      - my-todo-list:/var/lib/mysql
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

volumes:
  my-todo-list: